#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("OpenHack.Resource", IsApplication=true)]

namespace OpenHack
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int skills = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int monoandroidsplash = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080013
			public const int addSkill = 2131230739;
			
			// aapt resource value: 0x7f080011
			public const int addSkillToList = 2131230737;
			
			// aapt resource value: 0x7f080009
			public const int addSkillUser = 2131230729;
			
			// aapt resource value: 0x7f08000d
			public const int bioCreateUser = 2131230733;
			
			// aapt resource value: 0x7f08001b
			public const int button1 = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int button2 = 2131230748;
			
			// aapt resource value: 0x7f080015
			public const int confirm = 2131230741;
			
			// aapt resource value: 0x7f080008
			public const int confirmCreateUser = 2131230728;
			
			// aapt resource value: 0x7f080001
			public const int createAccountText = 2131230721;
			
			// aapt resource value: 0x7f080018
			public const int dontHaveAccount = 2131230744;
			
			// aapt resource value: 0x7f080014
			public const int duplicateWarning = 2131230740;
			
			// aapt resource value: 0x7f080016
			public const int emailField = 2131230742;
			
			// aapt resource value: 0x7f080003
			public const int emailFieldCreate = 2131230723;
			
			// aapt resource value: 0x7f080010
			public const int jobDesc = 2131230736;
			
			// aapt resource value: 0x7f08000e
			public const int jobTitle = 2131230734;
			
			// aapt resource value: 0x7f08001d
			public const int listView1 = 2131230749;
			
			// aapt resource value: 0x7f080019
			public const int login = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public const int loginTitle = 2131230746;
			
			// aapt resource value: 0x7f080002
			public const int nameFieldCreate = 2131230722;
			
			// aapt resource value: 0x7f08000b
			public const int newSkill = 2131230731;
			
			// aapt resource value: 0x7f080006
			public const int nextPage = 2131230726;
			
			// aapt resource value: 0x7f080017
			public const int passwordField = 2131230743;
			
			// aapt resource value: 0x7f080005
			public const int passwordFieldCreate = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int phoneFieldCreate = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int relativeLayout1 = 2131230720;
			
			// aapt resource value: 0x7f08000f
			public const int skillSpinner = 2131230735;
			
			// aapt resource value: 0x7f08000c
			public const int skillSpinnerUser = 2131230732;
			
			// aapt resource value: 0x7f080012
			public const int skillsList = 2131230738;
			
			// aapt resource value: 0x7f08000a
			public const int skillsListUser = 2131230730;
			
			// aapt resource value: 0x7f080007
			public const int textView1 = 2131230727;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Account_Creation = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Account_Creation_Page_2 = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Create_Job = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Login = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Main = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Mono_Android_Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
